# Generated by Django 3.2.21 on 2023-09-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0002_auto_20230927_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpickingproblem',
            name='part_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='planner',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='total_affected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='unit_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='work_order',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
