# Generated by Django 3.2.21 on 2023-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0003_auto_20230927_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpickingproblem',
            name='app_dept',
            field=models.CharField(choices=[('WRHS', 'Warehouse'), ('RTRN', 'Returns'), ('RUSH', 'Rushes'), ('INVC', 'InvControl'), ('PRDN', 'Production'), ('PTAW', 'PutAway'), ('RCVG', 'Receiving'), ('STUP', 'SetUp')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='department',
            field=models.CharField(choices=[('WRHS', 'Warehouse'), ('RTRN', 'Returns'), ('SHIP', 'Shipping'), ('INVC', 'InvControl'), ('PRNT', 'PrintRoom'), ('PRDN', 'Production'), ('CLNR', 'CleanRoom'), ('RCVG', 'Receiving'), ('STUP', 'SetUp')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='line',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('06A', '06A'), ('07', '07'), ('08', '08'), ('09', '09')], default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='shift',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd')], default='0', max_length=1),
        ),
    ]
