# Generated by Django 3.2.21 on 2023-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0004_auto_20230929_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpickingproblem',
            old_name='planner',
            new_name='item_dsc',
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='app_dept',
            field=models.CharField(choices=[('PCKN', 'Picking'), ('RTRN', 'Returns'), ('RUSH', 'Rushes'), ('INVC', 'InvControl'), ('PRDN', 'Production'), ('PTAW', 'PutAway'), ('RCVG', 'Receiving'), ('STUP', 'SetUp')], default='N/A', max_length=4),
        ),
    ]
