# Generated by Django 3.2.21 on 2023-10-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0007_newpickingproblem_defect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpickingproblem',
            old_name='total_quantity',
            new_name='total_count',
        ),
    ]
