# Generated by Django 3.2.21 on 2023-10-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0008_rename_total_quantity_newpickingproblem_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPickingProblem',
            fields=[
                ('newpickingproblem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ppLRPDN.newpickingproblem')),
            ],
            bases=('ppLRPDN.newpickingproblem',),
        ),
    ]
