# Generated by Django 3.2.21 on 2023-10-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0009_finalpickingproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpickingproblem',
            name='appliesf',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='employee_usernamef',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='final_commentsf',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='final_reasonf',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='locationf',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='root_causef',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='statusf',
            field=models.CharField(choices=[('Finalize', 'Finalize')], default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='transaction_datef',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='finalpickingproblem',
            name='transaction_timef',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
