# Generated by Django 3.2.21 on 2023-10-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0010_auto_20231006_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpickingproblem',
            name='applied',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='employee_username',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='final_comments',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='final_reason',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='root_cause',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='status',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='transaction_date',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='newpickingproblem',
            name='transaction_time',
            field=models.CharField(default='N/A', max_length=255),
        ),
        
    ]
