# Generated by Django 3.2.21 on 2023-10-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0011_auto_20231006_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalPickingProblem',
        ),
    ]
