# Generated by Django 3.2.21 on 2023-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0013_alter_newpickingproblem_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpickingproblem',
            name='finalized_date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
