# Generated by Django 3.2.21 on 2023-10-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0015_alter_newpickingproblem_finalized_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpickingproblem',
            name='applied',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='finalized_date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
