# Generated by Django 3.2.21 on 2023-10-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0016_auto_20231016_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpickingproblem',
            name='app_dept',
            field=models.CharField(choices=[('PCKN', 'Picking'), ('RTRN', 'Returns'), ('RUSH', 'Rushes'), ('INVC', 'InvControl'), ('PRDN', 'Production'), ('PTAW', 'PutAway'), ('RCVG', 'Receiving'), ('STUP', 'SetUp')], default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='defect',
            field=models.CharField(choices=[('Dirty', 'Dirty'), ('Damaged', 'Damaged'), ('Wrong', 'Wrong'), ('Incomplete', 'Incomplete'), ('Excess', 'Excess'), ('Short', 'Short'), ('Expiration', 'Expiration'), ('Wrong UoM', 'Wrong UoM'), ('Other', 'Other'), ('WrngPrt', 'Wrong Part'), ('MxPrt', 'Mixed Part'), ('WrngQty', 'Wrong Quantity'), ('WrngLoc', 'Wrong Location'), ('Clearance', 'Clearance'), ('Photos', 'Photos'), ('Missing', 'Missing')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='department',
            field=models.CharField(choices=[('WRHS', 'Warehouse'), ('RTRN', 'Returns'), ('SHIP', 'Shipping'), ('INVC', 'InvControl'), ('PRNT', 'PrintRoom'), ('PRDN', 'Production'), ('CLNR', 'CleanRoom'), ('RCVG', 'Receiving'), ('STUP', 'SetUp')], default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='employee_username',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='final_comments',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='final_reason',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='item_dsc',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='line',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('06A', '06A'), ('07', '07'), ('08', '08'), ('09', '09')], default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='location',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='part_number',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='root_cause',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='status',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='transaction_time',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='unit_type',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='work_order',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
