# Generated by Django 3.2.21 on 2023-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0017_auto_20231016_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpickingproblem',
            name='finalized_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='newpickingproblem',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
