# Generated by Django 3.2.21 on 2023-10-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0018_auto_20231016_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpickingproblem',
            name='transaction_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
