# Generated by Django 3.2.21 on 2023-10-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0022_newpickingproblem_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpickingproblem',
            name='zone',
        ),
    ]
