# Generated by Django 3.2.21 on 2023-10-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0023_remove_newpickingproblem_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpickingproblem',
            options={'permissions': [('can_delete_pp', 'Can delete picking problem')]},
        ),
    ]
