# Generated by Django 3.2.21 on 2023-11-29 23:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0026_employee_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('reference_number', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('badge_number', models.CharField(max_length=20, verbose_name='Badge Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('item_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Number')),
                ('work_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Order')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='Item Description')),
                ('supplier', models.CharField(blank=True, choices=[('Picking', 'Picking'), ('Setup', 'Setup'), ('Receiving', 'Receiving'), ('Production', 'Production'), ('Inventory Control', 'Inventory Control')], max_length=255, null=True, verbose_name='Supplier')),
                ('point_of_discovery', models.CharField(choices=[('Production', 'Production'), ('Setup', 'Setup'), ('Planning', 'Planning'), ('Internal', 'Internal')], max_length=200, verbose_name='Point of Discovery')),
                ('badge_number_pod', models.CharField(max_length=20, verbose_name='Badge Number')),
                ('non_conformances', multiselectfield.db.fields.MultiSelectField(choices=[('W01', 'Dirty/damaged rejected product'), ('W02', 'Product not labeled'), ('W03', 'Missing item(s)'), ('W04', 'Mixed orders WOs/waves'), ('W05', 'Order missing'), ('W06', 'Picked over'), ('W07', 'Packaging'), ('W08', 'Received wrong item'), ('W09', 'Expired product'), ('W10', 'Picked short'), ('W13', 'Dirty work area e.g., picker, cart, etc.'), ('W14', 'Improper use of equipment (horn, etc.)'), ('W15', 'Failure to follow procedure/directions'), ('W18', 'Exposed product (not put away in bag)'), ('W19', 'Gross overage/shortage (75\\%\\ or greater)'), ('W21', 'Trash found on location'), ('W22', 'Received wrong quantity'), ('W23', 'Failure to perform area clearance'), ('W24', 'Incorrect labeling of product'), ('W26', 'Missing expiration date'), ('W28', 'Received multiple lots under one lot number'), ('W29', 'Listed wrong expiration date'), ('W30', 'Incorrect lot number recorded'), ('W31', 'Overages not put away in boxes'), ('W32', 'Product found in wrong location'), ('W33', 'Product stocked too high to pick/cart from'), ('W34', 'Improper FIFO'), ('W35', 'Work order not updated'), ('W36', 'Improper documentation'), ('W37', 'Improper staging of product'), ('W38', 'Other (document other below)'), ('W39', 'Product found in trash'), ('W40', 'Picked wrong component'), ('W41', 'Missed transaction'), ('W42', 'Item left on location'), ('W43', 'Item stocked in wrong location'), ('W44', 'Safety violation')], max_length=111)),
                ('lead_supervisor', models.CharField(max_length=255, verbose_name='Lead Supervisor')),
                ('investigation_date', models.DateField(blank=True, null=True, verbose_name='Investigation Date')),
                ('training', models.BooleanField(default=False, verbose_name='Training')),
                ('training_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('counseling', models.BooleanField(default=False, verbose_name='Counseling')),
                ('counseling_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('disciplinary_action', models.BooleanField(default=False, verbose_name='Disciplinary Action')),
                ('disciplinary_action_date', models.DateField(blank=True, null=True, verbose_name='Disciplinary Action Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('employee_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Signature')),
                ('employee_signature_date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='employee_db',
        ),
    ]
