# Generated by Django 3.2.21 on 2023-12-01 18:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0027_auto_20231129_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='reference_number',
            new_name='ticket_number',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='non_conformances',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('W01', 'Dirty/damaged rejected product'), ('W02', 'Product not labeled'), ('W03', 'Missing item(s)'), ('W04', 'Mixed orders WOs/waves'), ('W05', 'Order missing'), ('W06', 'Picked over'), ('W07', 'Packaging'), ('W08', 'Received wrong item'), ('W09', 'Expired product'), ('W10', 'Picked short'), ('W13', 'Dirty work area e.g., picker, cart, etc.'), ('W14', 'Improper use of equipment (horn, etc.)'), ('W15', 'Failure to follow procedure/directions'), ('W18', 'Exposed product (not put away in bag)'), ('W19', 'Gross overage/shortage (75% or greater)'), ('W21', 'Trash found on location'), ('W22', 'Received wrong quantity'), ('W23', 'Failure to perform area clearance'), ('W24', 'Incorrect labeling of product'), ('W26', 'Missing expiration date'), ('W28', 'Received multiple lots under one lot number'), ('W29', 'Listed wrong expiration date'), ('W30', 'Incorrect lot number recorded'), ('W31', 'Overages not put away in boxes'), ('W32', 'Product found in wrong location'), ('W33', 'Product stocked too high to pick/cart from'), ('W34', 'Improper FIFO'), ('W35', 'Work order not updated'), ('W36', 'Improper documentation'), ('W37', 'Improper staging of product'), ('W38', 'Other (document other below)'), ('W39', 'Product found in trash'), ('W40', 'Picked wrong component'), ('W41', 'Missed transaction'), ('W42', 'Item left on location'), ('W43', 'Item stocked in wrong location'), ('W44', 'Safety violation')], max_length=111),
        ),
    ]
