# Generated by Django 3.2.21 on 2023-12-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0028_auto_20231201_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='badge_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Badge Number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lead_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead Supervisor'),
        ),
    ]
