# Generated by Django 3.2.21 on 2023-12-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0030_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpickingproblem',
            name='comment',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
