# Generated by Django 3.2.21 on 2023-12-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0031_alter_newpickingproblem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpickingproblem',
            name='reference_number',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
