# Generated by Django 3.2.21 on 2023-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppLRPDN', '0032_alter_newpickingproblem_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpickingproblem',
            name='job_number',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
